### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by roblabla** [dignifiedquire/num-bigint#11]
With `alloc` now stable since 1.36 (released last month) it'd be nice to have this crate support no_std (perhaps behind a feature gate to keep compatibility with rust 1.31). My end-goal is to have the [RSA crate](https://github.com/RustCrypto/RSA) working in no_std environments.

**Comment by dignifiedquire** [comment]
I agree, this would be great, I don't have any experience in turning things `no_std` compatible though, so happy to get some help with this.

**Comment by roblabla** [comment]
Awesome, I'll get to work on this then.
