### ISSUE TITLE
Support for Rand v0.8

### ISSUE THREAD

**Issue by alechenthorne** [dignifiedquire/num-bigint#23]
Simply upgrading the dependency to Rand v0.8 doesn't work as it seems the rand::AsBytesSliceMut trait has been removed and more info can be seen in [this comment](https://github.com/rust-random/rand/issues/1080#issuecomment-748615874).

This requires for gen_biguint to move to using the higher level `fill` method rather than the `fill_bytes` method on the data.

I have a [working example](https://github.com/alechenthorne/num-bigint/commit/ed0a5de2500e0e0084270beb84d9c981a3b52a8f), but would be curious the thoughts on using fill directly.

**Comment by phayes** [comment]
I have a PR for this here: https://github.com/dignifiedquire/num-bigint/pull/25

**Comment by dignifiedquire** [comment]
Still waiting a little bit longer to propagate this through libraries, breaking `rand` changes are quite painful and dividing in the ecosystem. Last time around it took months for the ecosystem to rally behind the latest version.

**Comment by phayes** [comment]
One approach could be to track a separate `alpha` branch that contains the updated rand. It looks like this is the approach that the dalek-cryptography folks will be taking (https://github.com/dalek-cryptography/curve25519-dalek/pull/338). It's worth noting that `curve25519` is related to `num-bigint-dig` via `num-bigint-dig <- pgp -> ed25519-dalek -> curve25519-dalek`.

**Comment by dignifiedquire** [comment]
I don't think I'll want an extra release cycle, I'll probably merge it soonish to master and then do a release once things are looking good.

**Comment by sabify** [comment]
@dignifiedquire Would you mind to release the update for crate.io due to latest changes for support rand 0.8?

**Comment by dignifiedquire** [comment]
Released `0.7` with rand@0.8 support

**Comment by sabify** [comment]
Thanks!
