### ISSUE TITLE
New patch release for autocfg bump?

### ISSUE THREAD

**Issue by adamchalmers** [dignifiedquire/num-bigint#33]
Hi all! We use this project in our product, and it's currently the only crate in our tree which uses autocfg 0.1 :) I notice that as of commit 41264ca629530d51db33e6c2cd7e95f496594154 you've upgraded to autocfg 1, which is great! I'd like to pull this into my project. Could you please cut a new patch release with this change, so that everyone on crates.io can upgrade and remove the old autocfg from their tree? Thank you!

**Comment by rickyhosfelt** [comment]
Any chance for a version bump?

**Comment by dignifiedquire** [comment]
New release is out `0.8.0`
