### ISSUE TITLE
Publish a 0.8 after change to Edition 2021

### ISSUE THREAD

**Issue by poliorcetics** [dignifiedquire/num-bigint#36]
This would notably unblock https://github.com/RustCrypto/RSA/pull/135

**Comment by mat-gas** [comment]
would be really nice indeed, nice catch

**Comment by paolobarbolini** [comment]
Also required for https://github.com/launchbadge/sqlx/pull/1625 to update all of RustCrypto's crates at once

**Comment by paolobarbolini** [comment]
Ping @dignifiedquire

**Comment by dignifiedquire** [comment]
New release is out `0.8.0`
