### ISSUE TITLE
`probably_prime` is skipping lots of primes, including primes below 2⁶⁴

### ISSUE THREAD

**Issue by darconeous** [dignifiedquire/num-bigint#51]
From the documentation for [`probably_prime`](https://docs.rs/num-bigint-dig/latest/num_bigint_dig/prime/fn.probably_prime.html):

> ProbablyPrime is 100% accurate for inputs less than 2⁶⁴.  See Menezes et al., Handbook of Applied Cryptography, 1997, pp. 145-149, and FIPS 186-4 Appendix F for further discussion of the error probabilities.

I have found counterexamples which show this assertion to be false:

```rust
assert!(probably_prime(&BigUint::from_u64(1579751).unwrap(), 20));
assert!(probably_prime(&BigUint::from_u64(1884791).unwrap(), 20));
assert!(probably_prime(&BigUint::from_u64(3818929).unwrap(), 20));
assert!(probably_prime(&BigUint::from_u64(4080359).unwrap(), 20));
assert!(probably_prime(&BigUint::from_u64(4145951).unwrap(), 20));
```

All 5 of these prime numbers are lower than 2⁶⁴, yet none cause `probably_prime` to return true.

**Comment by dignifiedquire** [comment]
The algorithm is based on the implementation in `math/big` from golang, including the reference. So it would be good to check if there is an issue in either the original implementation, the go implementation, or just this implementation.

**Comment by darconeous** [comment]
Looks like it works fine in Go: https://go.dev/play/p/IfJc2JqaCjL

**Comment by dignifiedquire** [comment]
Thanks for checking, that is not good.

**Comment by dignifiedquire** [comment]
@darconeous I have a fix, at least for the primes you posted in https://github.com/dignifiedquire/num-bigint/pull/54

**Comment by darconeous** [comment]
In my initial testing, this seems to be performing much, much better. The output now looks equivalent to OpenSSL's `BN_is_prime` function.

**Comment by dignifiedquire** [comment]
Thanks a lot for reporting and testing!
